name: "LeanIX VSM Discovery"
description: "Integrate into your CI/CD pipeline to manage service and SBOM information automatically for your LeanIX VSM workspace"
inputs:
  host:
    description: "The LeanIX host where the connector is located, e.g.: eu.leanix.net"
    required: true
    default: "eu.leanix.net"
  api-token:
    description: "technical user token for VSM workspace"
    required: true
  service-name:
    description: "Name of the service. By default name of the repository is assumed."
    required: false
  service-description:
    description: "The description of the service."
    required: false
    default: ""
  additional-data:
    description: "A key-value object holding any additional metadata about the service you want to bring into VSM."
    required: false
  source-type:
    description: "The source system of the service e.g. CI/CD"
    required: false
    default: "cicd"
  sbom-path:
    description: "The location of the SBOM file that is generated in CycloneDX specification. Accepted only JSON format. Read me about in the documentation for generating the SBOM file correctly. By default bom.json (path: /bom.json) is attempted in the root folder."
    required: false
    default: "/bom.json"
runs:
  using: 'node16'
  main: 'dist/index.js'
