name: Generate and register service

on:
  push:
    branches:
      - main

jobs:
  post-deploy:
    name: Post Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Generate SBOM
        run:  |
          npm install --global @cyclonedx/cyclonedx-npm
          cyclonedx-npm --output-file "bom.json"

      - name: VSM discovery
        uses: leanix/vsm-discovery-github-action@main
        with:
          api-token: ${{ env.VSM_LEANIX_API_TOKEN }}